obj-$(CONFIG_SND_SOC_DBMDX_ALEXA) := dbmdx.o
obj-$(CONFIG_SND_SOC_DBMDX_ALEXA) += dbmdx-spi.o
obj-$(CONFIG_SND_SOC_DBMDX_ALEXA) += dbmdx-i2c.o
obj-$(CONFIG_SND_SOC_DBMDX_ALEXA) += dbmdx-i2c-d2.o
obj-$(CONFIG_SND_SOC_DBMDX_ALEXA) += dbmdx-i2c-d4.o
obj-$(CONFIG_SND_SOC_DBMDX_ALEXA) += dbmdx-spi-d2.o
obj-$(CONFIG_SND_SOC_DBMDX_ALEXA) += dbmdx-spi-d4.o
obj-$(CONFIG_SND_SOC_DBMDX_ALEXA) += dbmdx-uart-d2.o
obj-$(CONFIG_SND_SOC_DBMDX_ALEXA) += dbmdx-uart-d4.o
obj-$(CONFIG_SND_SOC_DBMDX_ALEXA) += dbmdx-uart.o
obj-$(CONFIG_SND_SOC_DBMDX_ALEXA) += dbmdx-i2s.o
obj-$(CONFIG_SND_SOC_DBMDX_ALEXA) += dbmdx-customer.o
obj-$(CONFIG_SND_SOC_DBMDX_ALEXA) += dbmdx-cdev.o
obj-$(CONFIG_SND_SOC_DBMDX_I2S_CAPTURE_DEVICE) += dbmdx-snd-codec.o
obj-$(CONFIG_SND_SOC_DBMDX_SND_CAPTURE) += dbmdx-snd.o
obj-$(CONFIG_SND_SOC_DBMDX_SND_CAPTURE) += dbmdx-snd-pcm.o

